### PR TITLE
Support for saml2:conditions on AuthnRequest

### PR DESCRIPTION
**Pull request by Zyano**
This PR attempts to add to support for saml2:Conditions for AuthnRequests. The reason being Audience and  it's surronding tags are expected by the Danish public sector innative "ContextHandler" as part of their "Den fælleskommunale rammearkitektur".

There are a few more feilds and types that could be implmented before this feature can be considered complete for requests.
Expected attributes for the "Condition" element tree was found here: https://docs.oasis-open.org/security/saml/v2.0/saml-schema-assertion-2.0.xsd

There is no support for Saml2Response handling in this PR.

I'm creating the PR in order to figure out if this is someting you want as part of the pakcage at all (@Revsgaard)

Best Regards
Stefan

### CODE REVIEW

**Comment by Revsgaard** [comment]
Hi Stefan

Thank you very much. Yes I would like to add this functionality to the package. 

We also need to add the read Saml2Response functionality used in a PR. Is it possible for you to add the functionality or is it something I have to do?

Have you added all the fields required by "Den fælleskommunale rammearkitektur"?

Regards Anders

**Comment by Zyano** [comment]
Hi Anders,

I've added just enough to get the integration to Kombit ContextHandler working with the ITFoxtech package. 
There are few more fields that should be implemented on the Conditions element which I plan on doing. As for the response handling, it's something I haven't looked into yet. The usability of Conditions on the request is also something that could use some work. The current implementation requires the following to be on the Saml2AuthnRequest object.

`binding.Bind(new Saml2AuthnRequest(config)
            {
                Conditions = new Condition()
                {
                    Items = new List<ConditionAbstract>()
                    {
                        new AudienceRestriction()
                        {
                            Audiences = new List<Audience>()
                            {
                                new Audience()
                                {
                                    Uri = config.Issuer
                                }
                            }
                        }
                    }
                }
            }).ToActionResult();`

Which is not very user friendly. 

Taking a quick look at the saml spec for requets it appears that the Issuer/EntityId is often used as the Audience when sending requests.

When receiving a saml2repsonse it appears to mostly be a "verify that this was intended for me" feature.

**Comment by Zyano** [comment]
Hi Anders,

I've pulled the latest changes from master and implemented the remaining fields on the Conditions request object. 
The implementation of Saml2Response has not been started and I'm unsure if it's something you wish to do or something I need to look at.

**Comment by Revsgaard** [comment]
It looks great. I would very much appreciate it if you could look into the Saml2Response implementation. 

I have released a [beta version (4.6.0-beta1)](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.6.0-beta1) with your changes. Please test and let me know if it works.

**Pull request merged**
