### PR TITLE
Added keyInfoName property in Saml2Configuration

### PR DESCRIPTION
**Pull request by aducng99**
I added a new property to the Saml2Configuration that we need for signing.
Please let me know if this is fine, thanks!

### CODE REVIEW

**Comment by Revsgaard** [comment]
Thanks I'll look into it.

**Comment by aducng99** [comment]
Any update on this? We would like to use this change for our production release soon.

**Comment by Revsgaard** [comment]
Is the reason for having a KeyInfoName to associate the signature with a certificate, optionally in metadata? I wonder if the KeyInfoName can somehow be exposed in the metadata?

**Comment by aducng99** [comment]
The KeyName is indeed returned in the metadata we generate but it still has to be passed into our AuthnRequest that we send to our provider as they request it themselves so without this change, we cannot expose it.

**Comment by Revsgaard** [comment]
What about calculate key info name in Saml2SignedXml like in metadata [SsoDescriptorType.cs:line93](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/77aeafa91a1f8dc6eace6cd281d6d6c5608cbd44/src/ITfoxtec.Identity.Saml2/Schemas/Metadata/SsoDescriptorType.cs#L93)?

See the https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/6012c89a6dd5c9b73d1245fa67350aa2597b5d63 commit.

**Comment by aducng99** [comment]
I'm not sure if we are able to retrieve the KeyInfoName like in SsoDescriptorType.cs but I can try testing that out locally and see if we can get it back in our AuthnRequest and let you know.

**Comment by Revsgaard** [comment]
I think it should work, released in [version 4.13.1](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.13.1).

**Comment by aducng99** [comment]
Ok I was able to retrieve the keyname similarly this way too. Thank you for the help and release!

**Comment by Revsgaard** [comment]
The KeyInfoName is configurable in version [4.13.2](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.13.2), please see https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/issues/225.

**Pull request merged**
