### PR TITLE
updated signature with namespace alias. also added keyName element to…

### PR DESCRIPTION
**Pull request by kpadmanabhan**
… signatures

### CODE REVIEW

**Comment by kpadmanabhan** [comment]
@Revsgaard : can you please take a look at this? we will need to create another beta release if the changes are good.

**Comment by Revsgaard** [comment]
A test SAML authn response with the current signature:

```
<saml2p:Response xmlns:saml2p="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" ID="_2defd127-2f8d-4f36-b64a-c5c6a874a98f" Version="2.0" IssueInstant="2022-11-22T10:19:47.334Z" Destination="https://localhost:44306/Auth/AssertionConsumerService" InResponseTo="_5591e97d-6e76-4f6b-96d9-e12512636601">
  <saml2:Issuer>itfoxtec-testidpcore</saml2:Issuer>
  <Signature xmlns="http://www.w3.org/2000/09/xmldsig#">
    <SignedInfo>
      <CanonicalizationMethod Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
      <SignatureMethod Algorithm="http://www.w3.org/2001/04/xmldsig-more#rsa-sha256" />
      <Reference URI="#_2defd127-2f8d-4f36-b64a-c5c6a874a98f">
        <Transforms>
          <Transform Algorithm="http://www.w3.org/2000/09/xmldsig#enveloped-signature" />
          <Transform Algorithm="http://www.w3.org/2001/10/xml-exc-c14n#" />
        </Transforms>
        <DigestMethod Algorithm="http://www.w3.org/2001/04/xmlenc#sha256" />
        <DigestValue>Rfc1yEl9DCIRQeXoK+K5Yf6J7+BgpB0nNHxMOaOQwGw=</DigestValue>
      </Reference>
    </SignedInfo>
 <SignatureValue>bn08BJHK...PQ30brg==</SignatureValue>
    <KeyInfo>
      <X509Data>
        <X509Certificate>MIIDKj...SPArTQ==</X509Certificate>
      </X509Data>
    </KeyInfo>
  </Signature>
  <saml2p:Status>
    <saml2p:StatusCode Value="urn:oasis:names:tc:SAML:2.0:status:Success" />
  </saml2p:Status>
  <saml:Assertion ID="_847154eb-8de6-4b40-82dc-c6ef415acfda" IssueInstant="2022-11-22T10:19:47.334Z" Version="2.0" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion">
    <saml:Issuer>itfoxtec-testidpcore</saml:Issuer>
    <saml:Subject>
      <saml:NameID Format="urn:oasis:names:tc:SAML:2.0:nameid-format:persistent">abcd</saml:NameID>
      <saml:SubjectConfirmation Method="urn:oasis:names:tc:SAML:2.0:cm:bearer">
        <saml:SubjectConfirmationData InResponseTo="_5591e97d-6e76-4f6b-96d9-e12512636601" NotOnOrAfter="2022-11-22T10:24:47.334Z" Recipient="https://localhost:44306/Auth/AssertionConsumerService" />
      </saml:SubjectConfirmation>
    </saml:Subject>
    <saml:Conditions NotBefore="2022-11-22T10:19:47.334Z" NotOnOrAfter="2022-11-22T11:19:47.334Z">
      <saml:AudienceRestriction>
        <saml:Audience>itfoxtec-testwebappcore</saml:Audience>
      </saml:AudienceRestriction>
    </saml:Conditions>
    <saml:AttributeStatement>
      <saml:Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/upn">
        <saml:AttributeValue>abcd@email.test</saml:AttributeValue>
      </saml:Attribute>
      <saml:Attribute Name="http://schemas.xmlsoap.org/ws/2005/05/identity/claims/emailaddress">
        <saml:AttributeValue>abcd@someemail.test</saml:AttributeValue>
      </saml:Attribute>
    </saml:AttributeStatement>
    <saml:AuthnStatement AuthnInstant="2022-11-22T10:19:47.334Z" SessionIndex="07aa1eac-f93f-4b44-932d-0654faacbbec">
      <saml:AuthnContext>
        <saml:AuthnContextClassRef>urn:oasis:names:tc:SAML:2.0:ac:classes:PasswordProtectedTransport</saml:AuthnContextClassRef>
      </saml:AuthnContext>
    </saml:AuthnStatement>
  </saml:Assertion>
</saml2p:Response>
```

**Comment by Revsgaard** [comment]
Okay thanks. 

I can see it is SHA 1, today SHA 256 should be used.

**Comment by kpadmanabhan** [comment]
> Okay thanks.
> 
> I can see it is SHA 1, today SHA 256 should be used.

totally agree on SHA256. We are using SHA256 and specifying the same in signing algorithm.

**Comment by kpadmanabhan** [comment]
> I can not add this the code into the SignDocument method, It need to be done in a smoother way and with only one call to the ComputeSignature. Hopefully it is possible to make .NET calculate a signature with the wanted structure.
> 
> ```
>         // workaround for adding ds: for signature
> 
>         // get signature xml and add "ds:" prefix
>         var signature = signedXml.GetXml();
>         SetPrefix("ds", signature);
>         // Load modified signature back
>         signedXml.LoadXml(signature);
>         // this is workaround for overcoming a bug in the library
>         signedXml.SignedInfo.References.Clear();
>         // Recompute the signature
>         signedXml.ComputeSignature();
>         string recomputedSignature = Convert.ToBase64String(signedXml.SignatureValue);
>         // Replace value of the signature with recomputed one
>         ReplaceSignature(signature, recomputedSignature);
> 
>         xmlDocument.DocumentElement.InsertAfter(xmlDocument.ImportNode(signature, true), issuer);
> ```
> 
> Please past in a XML signature element with the structure you want.

Do you see a way to pass in the xmdigsig namespace alias to `ComputeSignature()` so that `signedXml.GetXml()` returns the xml with the namespace? I couldn't get that to work other than the way done in this PR. We are not tampering the signature here. But to get the signature in expected format, we are forced to compute the base64 encoded signature twice.

Also `KeyName` property added to `KeyInfo` is important as this is a mandatory field.

**Comment by Revsgaard** [comment]
Regarding "Also `KeyName` property added to `KeyInfo` is important as this is a mandatory field." Do you mean the KeyInfo element Id in metadata?

```
<m:KeyDescriptor use="signing">
<KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#" Id="Pw1c4nAiyF0cDut5Hl4iH/7g5Ao=">
<X509Data>
<X509Certificate>MIID...ShsKw==</X509Certificate>
</X509Data>
</KeyInfo>
</m:KeyDescriptor>
```

**Comment by kpadmanabhan** [comment]
> Regarding "Also `KeyName` property added to `KeyInfo` is important as this is a mandatory field." Do you mean the KeyInfo element Id in metadata?
> 
> ```
> <m:KeyDescriptor use="signing">
> <KeyInfo xmlns="http://www.w3.org/2000/09/xmldsig#" Id="Pw1c4nAiyF0cDut5Hl4iH/7g5Ao=">
> <X509Data>
> <X509Certificate>MIID...ShsKw==</X509Certificate>
> </X509Data>
> </KeyInfo>
> </m:KeyDescriptor>
> ```

no. that wasn't generating the right xml element. change done in this PR
`          var keyinfo = new KeyInfo();
            keyinfo.AddClause(new KeyInfoName(Guid.NewGuid().ToString()));
            keyinfo.AddClause(new KeyInfoX509Data(certificate, CertificateIncludeOption));`

this will generate something like 
`       <KeyInfo>
            <KeyName>f4882447-c07a-45c8-9a0f-4f7ff689d542</KeyName>
            <X509Data>
                <X509Certificate>MIIJYjCCB0qgAwIBAgIULuP...D+1IUfE</X509Certificate>
            </X509Data>
        </KeyInfo>`

**Comment by Revsgaard** [comment]
Adding an XML namespace prefix to the Signature element is really a hard thing to do right in .NET (and ugly).

The IdP should not require to use a namespace prefix, the signature is valid with and without.
It is probably most of a Java thing
- https://stackoverflow.com/a/66393296/8382203
- https://www.linkedin.com/pulse/how-add-prefix-xml-signature-element-c-rony-meyer/

**Nonetheless**
There can be added a namespace prefix to only the Signature element and not the sub element. This without invalidating the signature. Can be done by overwinding the GetXml method in the Saml2SignedXml class.

    public new XmlElement GetXml()
    {
        var element = m_signature.GetXml();

        var doc = element.ToXmlDocument();
        doc.DocumentElement.Prefix = "ds";
            
        return doc.DocumentElement;
    }

Would that maybe work?

**Comment by Revsgaard** [comment]
Changed to use KeyInfo Name insted of ID
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/4b52cdd359aac77905108a930bdcdedd7298c4c1

**Comment by kpadmanabhan** [comment]
> 

@Revsgaard  May be we park this for the time. `KeyName` change I see that you have taken to master. Can you please make a release with that? If this is passing the gate, then we might not need the "ds" prefix.

**Comment by Revsgaard** [comment]
Key info name released in https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.8.3-beta4

**Pull request closed without merging**
