### PR TITLE
adding unique id / name for a key

### PR DESCRIPTION
**Pull request by kpadmanabhan**

### CODE REVIEW

**Comment by kpadmanabhan** [comment]
@Revsgaard can you pls check this?

I have a requirement like this from IdP to support this in SP metadata. However, neither `KeyInfo` class, nor the `GetXml()` of `KeyInfo` support this. I can add an extension to this, but then we cannot use the `GetXml()` of `KeyInfo` class anymore. That will also have another implementation. Shall I do that in your project or do you see a better way to achieve this? 

3 dashes (---) means parent
4 dashes (----) means child of the parent above

---KeyInfo                  1
----KeyName             1                       Contains the name which identifies the key.
----X509Data            1                        Contains the encoded PKIOverheid X509 certificate with the public key.

**Comment by Revsgaard** [comment]
What about adding the key info ID like this? Would that work?

`keyinfo.Id = Convert.ToBase64String(certificate.GetCertHash());`

https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/blob/metadata_add_keyinfo_id/src/ITfoxtec.Identity.Saml2/Schemas/Metadata/SsoDescriptorType.cs#L85

**Comment by Revsgaard** [comment]
Resolved in this pull request https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/pull/124

**Comment by Revsgaard** [comment]
Key info name released in https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.8.3-beta4

**Pull request closed without merging**
