### PR TITLE
Saml2 authn request

### PR DESCRIPTION
**Pull request by kpadmanabhan**

### CODE REVIEW

**Comment by Revsgaard** [comment]
Why do you want to change "saml2" to "saml" and "saml2p" to "samlp"?

        public static readonly XName AssertionNamespaceNameX = XNamespace.Xmlns + "saml2";
to

        public static readonly XName AssertionNamespaceNameX = XNamespace.Xmlns + "saml";

and

        public static readonly XName ProtocolNamespaceNameX = XNamespace.Xmlns + "saml2p";
to

        public static readonly XName ProtocolNamespaceNameX = XNamespace.Xmlns + "samlp";

**Comment by kpadmanabhan** [comment]
> Why do you want to change "saml2" to "saml" and "saml2p" to "samlp"?
> 
> ```
>     public static readonly XName AssertionNamespaceNameX = XNamespace.Xmlns + "saml2";
> ```
> 
> to
> 
> ```
>     public static readonly XName AssertionNamespaceNameX = XNamespace.Xmlns + "saml";
> ```
> 
> and
> 
> ```
>     public static readonly XName ProtocolNamespaceNameX = XNamespace.Xmlns + "saml2p";
> ```
> 
> to
> 
> ```
>     public static readonly XName ProtocolNamespaceNameX = XNamespace.Xmlns + "samlp";
> ```

One of the IdP integrations unfortunately isn't accepting saml2p as namespace name. I believe the pattern they expect in the namespace name isnt configured to accept numbers. :(

**Comment by kpadmanabhan** [comment]
@Revsgaard : i have added a config based approach for the saml2p vs samlp. Can you please take a look?

**Comment by Revsgaard** [comment]
I have done the changes in the following commits. Do you think it solve the same problem?

https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/b23f5d74e0fabc383fed33e9cd8a446aa0c70d66
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/da73b1f6f82cd9a0b2e48c060d525d56e1c715fd
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/3fc688408e08733c5b0f1dd42eba6d5a7f328658
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/8754a929afff6f4c44b5ed6865278342e358a275
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/c4ad1ae5b6abb4484158b95c153c298d276a6363

**Comment by Revsgaard** [comment]
Released in https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.8.3-beta8

**Comment by Revsgaard** [comment]
Released in 4.8.4 - https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.8.4

**Pull request closed without merging**
