### PR TITLE
Add CustomCertificateValidator property to Saml2Configuration

### PR DESCRIPTION
**Pull request by schotime**
Allow a custom certificate validator to be used to Saml2Configuration when CertificateValidationMode set to Custom

### CODE REVIEW

**Comment by Revsgaard** [comment]
Hi, 

Thank you the contribution.

I only think this is possible in ASP.NET Core, and therefor changed the code to be limited to ASP.NET Core. Would you agree on the code?

Regards Anders

**Comment by schotime** [comment]
Thanks, looks look other that to question why you think this wouldn't be possible in ASP.NET full?

**Comment by Revsgaard** [comment]
You are right it is also possible in .NET Framework. Thank you very much for corrections :)
I have changed the code again. Would you agree this time?

**Comment by schotime** [comment]
I agree, do you want me to reset this PR to just my commit so the back and forth isn't there?

**Comment by Revsgaard** [comment]
It is fine I have changed a little in the namespaces, and thank you for your help. 
I have merged and the functionality will be in the next release.

**Comment by schotime** [comment]
Thank you. Appreciate the turn around. When do you estimate the next release?

**Comment by Revsgaard** [comment]
I have release version 4.0.1 containing the custom certificate validator functionality.

**Comment by schotime** [comment]
Awesome

**Pull request merged**
