### PR TITLE
Localization of Organization and ServiceName

### LINKED ISSUE #171: Suggestion: Possibility to add xml:lang attribute to xml elements / Possibility to add attributes to xml elements
Some parties require xml:lang to be defined for certain elements. For example Swedish Sambi requires xml:lang for the following elements:
IDPSSODescriptor/Organization/OrganizationName
IDPSSODescriptor/Organization/OrganizationDisplayName
IDPSSODescriptor/Organization/OrganizationURL.

### PR DESCRIPTION
**Pull request by TobiasMarklund**
Add Organization and ServiceName metadata localization types. 
Allow multiple translation for Organization elements. This is required by SAML Metadata specification.

Fixes #171

### CODE REVIEW

**Comment by andrecarrblad** [comment]
@Revsgaard Is it possible to release this? We also need it.

**Comment by Revsgaard** [comment]
I have merged with some changes https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/pull/202/commits/03efe264f2e27b4a9a49f8bd9569000cc14c07e3

**Comment by Revsgaard** [comment]
Thank you for contributing :)

**Comment by Revsgaard** [comment]
Released in version [4.10.9-beta3 ](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.10.9-beta3), please let me know if it works as expected.

**Comment by TobiasMarklund** [comment]
Works for me. 👍

**Pull request merged**
