### PR TITLE
Requested attribute fix

### PR DESCRIPTION
**Pull request by kpadmanabhan**

### CODE REVIEW

**Comment by kpadmanabhan** [comment]
@Revsgaard : need another change for the xsi type

**Comment by Revsgaard** [comment]
Makes this possible:

```
yield return new RequestedAttribute("urn:xxx", "test-value");
yield return new RequestedAttribute("urn:yyy", "123") { AttributeValueType = "xs:integer" };
```

**Comment by kpadmanabhan** [comment]
@Revsgaard : your version looks much cleaner. thank you. 
i added xml schema namespace as well into it, otherwise the xml is treated invalid as "xs" is not known.

**Comment by Revsgaard** [comment]
Okay thanks, I have change it a bit. Do you think this commit  https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/50d01e40968aedb4bcf3468e955f612526590177 would work?

Old XML
```
<m:RequestedAttribute Name="urn:yyy" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" isRequired="true">
  <saml:AttributeValue xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:integer">123</saml:AttributeValue>
</m:RequestedAttribute>
```

New XML 
```
<m:RequestedAttribute Name="urn:yyy" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" isRequired="true">
  <saml:AttributeValue xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xis="http://www.w3.org/2001/XMLSchema-instance" xis:type="xs:integer">123</saml:AttributeValue>
</m:RequestedAttribute>
```

**Comment by kpadmanabhan** [comment]
> Okay thanks, I have change it a bit. Do you think this commit [50d01e4](https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/50d01e40968aedb4bcf3468e955f612526590177) would work?
> 
> Old XML
> 
> ```
> <m:RequestedAttribute Name="urn:yyy" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" isRequired="true">
>   <saml:AttributeValue xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:integer">123</saml:AttributeValue>
> </m:RequestedAttribute>
> ```
> 
> New XML
> 
> ```
> <m:RequestedAttribute Name="urn:yyy" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic" isRequired="true">
>   <saml:AttributeValue xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xis="http://www.w3.org/2001/XMLSchema-instance" xis:type="xs:integer">123</saml:AttributeValue>
> </m:RequestedAttribute>
> ```

Looks good. Pls proceed.

**Comment by Revsgaard** [comment]
Thanks, released in https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.8.3-beta6

**Pull request closed without merging**
