### PR TITLE
Signature Validation with Multiple Signatures Present

### LINKED ISSUE #119: Signature Validation with Multiple Signatures
Been fighting with a problem for a couple of weeks now where I'm getting a  "Signature is invalid" exception when trying to validate a SAML2 Response. From looking at the POSTed response, everything looks kosher. I've tried a handful of ways of providing the Signing Certificate and keep ending up with the same result.

After lots of inheriting/overriding of classes/methods in the ITfoxtec package in order to debug, I found out that the overall document validation seems to be passing just fine, but there is also a signed assertion using the same certificate used to sign the document, that is failing. 

Through some research, I was able to track this down as seemingly a bug in .NET's SignedXml.CheckSignature method. 

**Additional Info:**
https://stackoverflow.com/questions/71446457/aws-sso-signature-verification-problems (StackOverflow of someone else experiencing the same problem using the ITfoxtec SAML implementation)

https://stackoverflow.com/questions/25394137/verify-signature-on-saml-assertion (StackOverflow issue that loosely talks about this CheckSignature issue and offers a workaround)

https://github.com/i8beef/SAML2/blob/master/src/SAML2/Utils/XmlSignatureUtils.cs (Another SAML2 implementation on github that works around this issue and references a page I've seen others on StackOverflow reference that talked about this issue which unfortunately no longer exists, https://support.microsoft.com/en-us/kb/952697)

### PR DESCRIPTION
**Pull request by willisd2**
fix: fixed an issue where signature validation would fail on the assertion if the SAML Response had multiple signatures in it (one for the Assertion, one for the Response as a whole)

fixes #119

### CODE REVIEW

**Comment by willisd2** [comment]
@Revsgaard Sorry for the late PR on this, but this should fix the issue I was experiencing with Assertion Signature validation when multiple signatures exist in a SAML Response, where both the Assertion and the Response as a whole have been signed. Part of the fix for me was to update to the 7.0.0 version of the System.Security.Cryptography.Xml, which it looks like you've already taken care of.

**Comment by Revsgaard** [comment]
Okay thanks, I'll have a look.

This PR is connected to this issue
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/issues/119

Do you have "&#13;" character in the message like described in this issue?
https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/issues/107

**Comment by Revsgaard** [comment]
I have changed slightly to add support for .NET Framework. 
Resolved in https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/commit/02eb45e9867f7d60a4dac958670d22729d38c620

**Comment by Revsgaard** [comment]
Released in https://github.com/ITfoxtec/ITfoxtec.Identity.Saml2/releases/tag/4.8.3-beta5

**Comment by willisd2** [comment]
> Do you have " " character in the message like described in this issue? #107
Just to follow up on this, the raw SAML Response I'm getting doesn't appear to have any spaces in the given certificate, nor a "&#13;" string.

**Comment by Revsgaard** [comment]
Okay, thank you for responding.

**Pull request closed without merging**
